FROM gradle:8.7-jdk21 AS build-stage

LABEL maintainer="ljh1223582317@gmail.com"

WORKDIR /app

COPY . /app

# Install supervisor
USER root

RUN apt-get update && apt-get clean

# Expose the port the application runs on
EXPOSE 8080

CMD [ "gradle", "bootRun" ]
