services:
  mysql:
    image: mysql:8.3
    container_name: mysql-container
    ports:
      - 43305:3306
    volumes:
      - stay-connect-mysql-data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: princess
      MYSQL_DATABASE: stayconnect


volumes:
   stay-connect-mysql-data: