services:
  nginx:
    image: ghcr.io/caterpillar-team/stay_connect_nginx
    build:
      context: ../
      dockerfile: docker/dockerfile-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/ssl:/etc/nginx/ssl
    depends_on:
      - stay_connect_app

  stay_connect_app:
    image: ghcr.io/caterpillar-team/stay_connect_app
    build:
      context: ../ # 프로젝트 루트 디렉토리를 빌드 컨텍스트로 지정
      dockerfile: docker/dockerfile-springboot
    container_name: spring-boot-container
    ports:
      - '8800:8080'
    environment:
      SPRING_DATASOURCE_URL: ${PRODUCTION_MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${PRODUCTION_MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PRODUCTION_MYSQL_PASSWORD}
    networks:
      - app-network
    env_file:
      - ../.env

networks:
  app-network:
    driver: bridge