# Use openjdk:21 base image for final stage
FROM openjdk:21-slim

# Set the working directory
WORKDIR /app

#  Copy .env file
COPY .env ./

# Copy the built application jar
COPY build/libs/StayConnect-0.0.2.jar /app/app.jar

# Expose the application port
EXPOSE 8080

# Run the application with wait-for-it
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "/app/app.jar"]