name: Delete All Artifacts

on:
  push:
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            *
