name: GITHUB ACTION CI/CD WITH AWS

on:
   push:
      branches: [main, develop]
   pull_request:
      branches: [main, develop]

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Set up JDK 21
           uses: actions/setup-java@v4
           with:
              distribution: 'temurin'
              java-version: '21'

         - name: Create environment variables file
           run: |
              echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
              echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
              echo "JSON_WEB_TOKEN_SECRET_KEY=${{ secrets.JSON_WEB_TOKEN_SECRET_KEY }}" >> .env
              echo "JSON_WEB_TOKEN_EXPIRATION_TIME=${{ secrets.JSON_WEB_TOKEN_EXPIRATION_TIME }}" >> .env
              echo "JSON_WEB_TOKEN_ISSUER=${{ secrets.JSON_WEB_TOKEN_ISSUER }}" >> .env
              echo "MYSQL_SERVER_URL=${{ secrets.MYSQL_SERVER_URL }}" >> .env
              echo "MYSQL_SERVER_USERNAME=${{ secrets.MYSQL_SERVER_USERNAME }}" >> .env
              echo "MYSQL_SERVER_PASSWORD=${{ secrets.MYSQL_SERVER_PASSWORD }}" >> .env
              echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
              echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
              echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
              echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env
              echo "PORTONE_API_URL=${{ secrets.PORTONE_API_URL }}" >> .env
              echo "PORTONE_API_KEY=${{ secrets.PORTONE_API_KEY }}" >> .env
              echo "PORTONE_SECRET_KEY=${{ secrets.PORTONE_SECRET_KEY }}" >> .env
              echo "PRODUCTION_MYSQL_URL=${{ secrets.PRODUCTION_MYSQL_URL }}" >> .env
              echo "PRODUCTION_MYSQL_ROOT_PASSWORD=${{ secrets.PRODUCTION_MYSQL_ROOT_PASSWORD }}" >> .env
              echo "PRODUCTION_MYSQL_DATABASE=${{ secrets.PRODUCTION_MYSQL_DATABASE }}" >> .env
              echo "PRODUCTION_MYSQL_USERNAME=${{ secrets.PRODUCTION_MYSQL_USERNAME }}" >> .env
              echo "PRODUCTION_MYSQL_PASSWORD=${{ secrets.PRODUCTION_MYSQL_PASSWORD }}" >> .env

         - name: Cache Gradle packages
           uses: actions/cache@v4
           with:
              path: |
                 ~/.gradle/caches
                 ~/.gradle/wrapper
              key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
              restore-keys: |
                 gradle-${{ runner.os }}-

         - name: Grant execute permission for gradlew
           run: chmod +x gradlew

         - name: Build with Gradle
           run: ./gradlew clean build -Dspring.profiles.active=prod -x test

         - name: Upload build artifacts
           uses: actions/upload-artifact@v4
           with:
              name: build-artifacts
              path: build/libs/StayConnect-0.0.2.jar
              retention-days: 1

         - name: Upload environment file artifacts
           uses: actions/upload-artifact@v4
           with:
              name: env-artifacts
              path: .
              retention-days: 1

   deploy:
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      needs: build

      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Download build artifacts
           uses: actions/download-artifact@v4
           with:
              name: build-artifacts
              path: build/libs

         - name: Download env artifacts
           uses: actions/download-artifact@v4
           with:
            name: env-artifacts
            path: .

         - name: Set up JDK 21
           uses: actions/setup-java@v4
           with:
              distribution: 'temurin'
              java-version: '21'

         - name: Set lower-case repository owner
           id: lowercase
           run: echo "::set-output name=repository_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')"

         - name: Set up QEMU
           uses: docker/setup-qemu-action@v3

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3

         - name: Log in to GitHub Container Registry
           uses: docker/login-action@v3
           with:
              registry: ghcr.io
              username: ${{ steps.lowercase.outputs.repo_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}

         - name: Build and push Nginx image
           uses: docker/build-push-action@v4
           with:
              context: .
              file: ./docker/dockerfile.nginx
              push: true
              tags: ghcr.io/${{ steps.lowercase.outputs.repository_owner }}/stay_connect_nginx:latest

         - name: Build and push Spring Boot image
           uses: docker/build-push-action@v4
           with:
              context: .
              file: ./docker/dockerfile.springboot
              push: true
              tags: ghcr.io/${{ steps.lowercase.outputs.repository_owner }}/stay_connect_app:latest

         - name: Build and push certbot image
           uses: docker/build-push-action@v4
           with:
              context: .
              file: ./docker/dockerfile.certbot
              push: true
              tags: ghcr.io/${{ steps.lowercase.outputs.repository_owner }}/stay_connect_certbot:latest

         - name: Transfer docker-compose-prod.yml to EC2 using SCP
           uses: appleboy/scp-action@master
           with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{ secrets.EC2_USER }}
              key: ${{ secrets.EC2_SSH_KEY }}
              port: ${{ secrets.EC2_PORT }}
              source: ./docker/docker-compose-prod.yml
              target: /home/${{ secrets.EC2_USER }}

         - name: Transfer .env to EC2 using SCP
           uses: appleboy/scp-action@master
           with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{ secrets.EC2_USER }}
              key: ${{ secrets.EC2_SSH_KEY }}
              port: ${{ secrets.EC2_PORT }}
              source: .env
              target: /home/${{ secrets.EC2_USER }}

         - name: Transfer init-letsencrypt.sh to EC2 using SCP
           uses: appleboy/scp-action@master
           with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{ secrets.EC2_USER }}
              key: ${{ secrets.EC2_SSH_KEY }}
              port: ${{ secrets.EC2_PORT }}
              source: init-letsencrypt.sh
              target: /home/${{ secrets.EC2_USER }}

         - name: SSH and deploy to EC2
           uses: appleboy/ssh-action@master
           with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{ secrets.EC2_USER }}
              key: ${{ secrets.EC2_SSH_KEY }}
              port: ${{ secrets.EC2_PORT }}
              script: |
                 if [ -f /home/${{ secrets.EC2_USER }}/docker/docker-compose-prod.yml ]; then
                   echo "File exists"
                   chmod 644 /home/${{ secrets.EC2_USER }}/docker/docker-compose-prod.yml
                   chmod +x init-letsencrypt.sh
                 else
                   echo "File does not exist"
                   exit 1
                 fi
                 docker-compose --env-file /home/${{ secrets.EC2_USER }}/.env -f /home/${{ secrets.EC2_USER }}/docker/docker-compose-prod.yml down
                 docker stop $(docker ps -aq)
                 docker rm $(docker ps -aq)
                 docker rmi -f $(docker images -q)
                 docker-compose --env-file /home/${{ secrets.EC2_USER }}/.env -f /home/${{ secrets.EC2_USER }}/docker/docker-compose-prod.yml pull
                 docker-compose --env-file /home/${{ secrets.EC2_USER }}/.env -f /home/${{ secrets.EC2_USER }}/docker/docker-compose-prod.yml up -d

   clear:
      runs-on: ubuntu-latest
      needs: deploy
      steps:
         - name: Delete Artifact
           uses: geekyeggo/delete-artifact@v5
           with:
              name: |
                 *

   dependency-submission:
      runs-on: ubuntu-latest
      permissions:
         contents: write

      steps:
         - uses: actions/checkout@v4
         - name: Set up JDK 21
           uses: actions/setup-java@v4
           with:
              java-version: '21'
              distribution: 'temurin'

         - name: Generate and submit dependency graph
           uses: gradle/actions/dependency-submission@v3.1.0
